spring:
  application:
    name: api-gateway
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/register
    username: emildobrev
  secret: 88deeacc8f37aac01ceeee14d8c2a5976dd3e9405c4b41358428e6e6952c9e0e5b83589e22cec123d84ffb48
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: user-route
          uri: lb://user
          predicates:
          - Path=/api/v1/auth/**,/api/v1/doctors/**,/api/v1/patients/**
          filters:
            - AuthenticationFilter
        - id: discovery-route-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - AuthenticationFilter
        - id: appointment-route
          uri: lb://appointment
          predicates:
          - Path=/api/v1/schedule/**,/api/v1/appointment/**
          filters:
            - AuthenticationFilter

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: trace
        route:
          RouteDefinitionLocator: info
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost