spring:
  application:
    name: api-gateway
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/register
    username: emildobrev
  secret: kTK1B6V1E4klYEnfjSDOepThdKcb0est4LK3HZLOsao
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: lb://user
          predicates:
          - Path=/api/v1/auth/**,/api/v1/doctors/**
          filters:
            - AuthenticationFilter
        - id: discovery-route-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - AuthenticationFilter
        - id: appointment-route
          uri: lb://appointment
          predicates:
            - Path=/appointment
          filters:
            - AuthenticationFilter

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: trace
        route:
          RouteDefinitionLocator: info
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
