package emil.dobrev.services.enums;

public enum Country {
    ARGENTINA("AR"),
    ANGOLA("AO"),
    AUSTRIA("AT"),
    AUSTRALIA("AU"),
    ARUBA("AW"),
    ÅLAND_ISLANDS("AX"),
    BOSNIA_AND_HERZEGOVINA("BA"),
    BELGIUM("BE"),
    BULGARIA("BG"),
    BOLIVIA("BO"),
    BRAZIL("BR"),
    THE_BHAMAS("BS"),
    CANADA("CA"),
    SWITZERLAND("CH"),
    CHINA("CN"),
    COLOMBIA("CO"),
    COSTA_RICA("CR"),
    CUBA("CU"),
    CZECH_REPUBLIC("CZ"),
    GERMANY("DE"),
    DENMARK("DK"),
    DOMINICAN_REPUBLIC("DO"),
    ECUADOR("EC"),
    SPAIN("ES"),
    FINLAND("FI"),
    FRANCE("FR"),
    UNITED_KINGDOM("GB"),
    ENGLAND("GB-ENG"),
    NORTHERN_IRELAND("GB-NIR"),
    SCOTLAND("GB-SCT"),
    WALES("GB-WLS"),
    GREECE("GR"),
    GUATEMALA("GT"),
    HONG_KONG("HK"),
    HONDURAS("HN"),
    CROATIA("HR"),
    HUNGARY("HU"),
    INDONESIA("ID"),
    IRELAND("IE"),
    INDIA("IN"),
    ISRAEL("IL"),
    ICELAND("IS"),
    ITALY("IT"),
    JAPAN("JP"),
    KAZAKHSTAN("KZ"),
    LESOTHO("LS"),
    LUXEMBOURG("LU"),
    MADAGASCAR("MG"),
    MARTINIQUE("MQ"),
    MALTA("MT"),
    MAURITIUS("MU"),
    MEXICO("MX"),
    MOZAMBIQUE("MZ"),
    NIGERIA("NG"),
    NETHERLANDS("NL"),
    NORWAY("NO"),
    PERU("PE"),
    PAKISTAN("PK"),
    PHILIPPINES("PH"),
    POLAND("PL"),
    PUERTO_RICO("PR"),
    PORTUGAL("PT"),
    PARAGUAY("PY"),
    RéUNION("RE"),
    ROMANIA("RO"),
    RUSSIA("RU"),
    SEYCHELLES("SC"),
    SWEDEN("SE"),
    SINGAPORE("SG"),
    SLOVENIA("SI"),
    SAO_TOME_AND_PRINCIPE("ST"),
    SLOVAKIA("SK"),
    TUNISIA("TN"),
    TURKEY("TR"),
    UKRAINE("UA"),
    UNITED_STATES("US"),
    URUGUAY("UY"),
    VENEZUELA("VE"),
    SOUTH_AFRICA("ZA"),
    ZIMBABWE("ZW");

    private String countryCode;

    Country(String countryCode) {
        this.countryCode = countryCode;
    }

    public String code() {
        return this.countryCode;
    }
}